
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`discord_id` VARCHAR(25) NOT NULL,
	`username` VARCHAR(100) NOT NULL,
	`discriminator` VARCHAR(4) NOT NULL,
	`avatar` VARCHAR(250) NULL,
	`banner` VARCHAR(250) NULL,
	`bot` TINYINT(1) NOT NULL DEFAULT 0,
	`webhook` TINYINT(1) NOT NULL DEFAULT 0,
	`ignore` TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `channels`;
CREATE TABLE `channels` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`discord_id` VARCHAR(25) NOT NULL,
	`name` VARCHAR(100) NULL,
	`topic` VARCHAR(4096) NULL,
	`type` TINYINT(2) NOT NULL DEFAULT 0,
	`flags` INT(11) NULL,
	`nsfw` TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `forwarder`;
CREATE TABLE `forwarder` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`fromChannel_id` INT(11) UNSIGNED NOT NULL,
	`toChannel_id` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `messages`;
CREATE TABLE `messages` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`channel_id` INT(11) UNSIGNED NOT NULL,
	`discord_id` VARCHAR(25) NOT NULL,
	`author` VARCHAR(100) NOT NULL,
	`content` VARCHAR(2000) NOT NULL,
	`type` TINYINT(2) NOT NULL,
	`flags` INT(11) NULL,
	`timestamp` INT(11) NOT NULL,
	`edited_timestamp` INT(11) NULL,
	`forwarded_on` INT(11) NULL,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `embeds`;
CREATE TABLE `embeds` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`message_id` INT(11) UNSIGNED NOT NULL,
	`url` VARCHAR(250) NULL,
	`author` VARCHAR(256) NULL,
	`title` VARCHAR(256) NULL,
	`description` VARCHAR(4096) NULL,
	`footer` VARCHAR(2048) NULL,
	`image` VARCHAR(250) NULL,
	`video` VARCHAR(250) NULL,
	`timestamp` INT(11) NULL,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `embed_fields`;
CREATE TABLE `embed_fields` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`embed_id` INT(11) UNSIGNED NOT NULL,
	`name` VARCHAR(256) NOT NULL,
	`value` VARCHAR(1024) NOT NULL,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `attachments`;
CREATE TABLE `attachments` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`message_id` INT(11) UNSIGNED NOT NULL,
	`discord_id` VARCHAR(25) NOT NULL,
	`url` VARCHAR(250) NOT NULL,
	`content_type` VARCHAR(255) NULL,
	`filename` VARCHAR(256) NOT NULL,
	`description` VARCHAR(1024) NULL,
	`size` INT(11) NOT NULL,
	PRIMARY KEY (`id`)
);
